name: build-apk
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk zip unzip libffi-dev libssl-dev libltdl-dev autoconf automake libtool pkg-config build-essential ccache
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.36
      - name: Build
        run: |
          buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
